debian/*.{pre,post}*: rework scriptlets, use updated templates, add missing templates, more and better quoting, fix other misc. errors within the scripts.

diff --git a/debian/libx2go-server-db-perl.postinst b/debian/libx2go-server-db-perl.postinst
--- a/debian/libx2go-server-db-perl.postinst
+++ b/debian/libx2go-server-db-perl.postinst
@@ -18,18 +18,18 @@ set -e
 # the debian-policy package
 
 
-case "$1" in
-	configure)
-		mkdir -p  /etc/x2go/x2gosql/passwords
-		chmod 700 /etc/x2go/x2gosql/passwords
-		touch     /etc/x2go/x2gosql/passwords/pgadmin
-		chmod 600 /etc/x2go/x2gosql/passwords/pgadmin
-		touch     /etc/x2go/x2gosql/passwords/mysqladmin
-		chmod 600 /etc/x2go/x2gosql/passwords/mysqladmin
+case "${1}" in
+	'configure')
+		mkdir -p    '/etc/x2go/x2gosql/passwords'
+		chmod '700' '/etc/x2go/x2gosql/passwords'
+		touch       '/etc/x2go/x2gosql/passwords/pgadmin'
+		chmod '600' '/etc/x2go/x2gosql/passwords/pgadmin'
+		touch       '/etc/x2go/x2gosql/passwords/mysqladmin'
+		chmod '600' '/etc/x2go/x2gosql/passwords/mysqladmin'
 
 		# the SQLite3 X2Go session db has to be accessed as uid x2gouser
-		if ! dpkg-statoverride --list /usr/lib/x2go/libx2go-server-db-sqlite3-wrapper >/dev/null; then
-		    dpkg-statoverride --add --update root x2gouser 2755 /usr/lib/x2go/libx2go-server-db-sqlite3-wrapper
+		if ! dpkg-statoverride --list '/usr/lib/x2go/libx2go-server-db-sqlite3-wrapper' >'/dev/null'; then
+		    dpkg-statoverride --add --update 'root' 'x2gouser' '2755' '/usr/lib/x2go/libx2go-server-db-sqlite3-wrapper'
 		fi
 
 		# setup up SQLite3 database, do nothing if PostgeSQL is already configured
@@ -37,30 +37,30 @@ case "$1" in
 		# Note: The below code exists in x2goserver.postinst and libx2go-server-db.postinst
 		# It will only succeed if both packages are installed. As we cannot influence the
 		# installation order, we handle the session DB creation in both packages. One of
-		# then should succeed.
-		if [ -x /usr/sbin/x2godbadmin ] && [ -f /etc/x2go/x2gosql/sql ] && egrep "^backend=sqlite.*" /etc/x2go/x2gosql/sql 1>/dev/null; then
-			if [ ! -f /var/lib/x2go/x2go_sessions ]; then
+		# them should succeed.
+		if [ -x '/usr/sbin/x2godbadmin' ] && [ -f '/etc/x2go/x2gosql/sql' ] && egrep '^backend=sqlite.*' '/etc/x2go/x2gosql/sql' 1>'/dev/null'; then
+			if [ ! -f '/var/lib/x2go/x2go_sessions' ]; then
 				x2godbadmin --createdb
 			else
 				# make sure db permissions are set correctly
-				chown -R root:x2gouser /var/lib/x2go
+				chown -R 'root:x2gouser' '/var/lib/x2go'
 				# egid x2gouser needs write access to the db dir (for temporary db journal file)
-				chmod 0770 /var/lib/x2go
+				chmod '0770' '/var/lib/x2go'
 				# ... and to the db file itself, of course
-				chmod 0660 /var/lib/x2go/x2go_sessions
+				chmod '0660' '/var/lib/x2go/x2go_sessions'
 				x2godbadmin --updatedb
 			fi
 		else
-			echo "X2Go is configured to use a non-SQLite DB backend, leaving the database alone."
+			echo 'X2Go is configured to use a non-SQLite DB backend, leaving the database alone.'
 		fi
 		;;
 
-	abort-upgrade|abort-remove|abort-deconfigure)
+	'abort-upgrade'|'abort-remove'|'abort-deconfigure')
 		;;
 
 	*)
-		echo "postinst called with unknown argument \`$1'" >&2
-		exit 1
+		echo "postinst called with unknown argument '${1}'" >&2
+		exit '1'
 		;;
 esac
 
@@ -69,6 +69,4 @@ esac
 
 #DEBHELPER#
 
-exit 0
-
-
+exit '0'
diff --git a/debian/libx2go-server-db-perl.postrm b/debian/libx2go-server-db-perl.postrm
--- a/debian/libx2go-server-db-perl.postrm
+++ b/debian/libx2go-server-db-perl.postrm
@@ -1,7 +1,8 @@
-#! /bin/sh
+#!/bin/sh
 # postrm script for libx2go-server-db-perl
-#
-# see: dh_installdeb(1)
+
+set -e
+
 # summary of how this script can be called:
 #        * <postrm> `remove'
 #        * <postrm> `purge'
@@ -10,29 +11,27 @@
 #        * <new-postrm> `abort-install'
 #        * <new-postrm> `abort-install' <old-version>
 #        * <new-postrm> `abort-upgrade' <old-version>
-#        * <disappearer's-postrm> `disappear' <r>overwrit>r> <new-version>
-# for details, see /usr/share/doc/packaging-manual/
+#        * <disappearer's-postrm> `disappear' <overwriter>
+#          <overwriter-version>
+# for details, see http://www.debian.org/doc/debian-policy/ or
+# the debian-policy package
 
-set -e
 
+case "${1}" in
+	'purge')
+		echo 'Removing X2Go session database' >&2
+		rm -vf '/var/lib/x2go/x2go_sessions'
+		rm -vf '/etc/x2go/x2gosql/passwords/pgadmin'
+		rm -vf '/etc/x2go/x2gosql/passwords/mysqladmin'
 
-case "$1" in
-
-	purge)
-		echo "Removing X2Go session database" >&2
-		rm -vf /var/lib/x2go/x2go_sessions
-		rm -vf /etc/x2go/x2gosql/passwords/pgadmin
-		rm -vf /etc/x2go/x2gosql/passwords/mysqladmin
-
-		rm -Rf /etc/x2go/sql
-		[ -d '/etc/x2go' ] && rmdir --ignore-fail-on-non-empty /etc/x2go
-
+		rm -Rf '/etc/x2go/sql'
+		[ -d '/etc/x2go' ] && rmdir --ignore-fail-on-non-empty '/etc/x2go'
 		;;
-	remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
+	'remove'|'upgrade'|'failed-upgrade'|'abort-install'|'abort-upgrade'|'disappear')
 		;;
 	*)
-		echo "postrm called with unknown argument \`$1'" >&2
-		exit 0
+		echo "postrm called with unknown argument '${1}'" >&2
+		exit '1'
 		;;
 esac
 
@@ -41,4 +40,4 @@ esac
 
 #DEBHELPER#
 
-exit 0
+exit '0'
