debian/x2goserver*{pre,post}*: rework scriptlets, use updated templates, add missing templates, more and better quoting, fix other misc. errors within the scripts.

diff --git a/debian/x2goserver-common.postinst b/debian/x2goserver-common.postinst
--- a/debian/x2goserver-common.postinst
+++ b/debian/x2goserver-common.postinst
@@ -17,54 +17,52 @@ set -e
 # for details, see http://www.debian.org/doc/debian-policy/ or
 # the debian-policy package
 
-case "$1" in
-	configure)
-
+case "${1}" in
+	'configure')
 		###
 		### setup X2Go user account (needed for session database)
 		###
 
 		# setup x2gouser and group
-		if ! getent group x2gouser >/dev/null; then
-			echo "Creating x2gouser group." >&2
-			addgroup --system x2gouser
+		if ! getent 'group' 'x2gouser' >'/dev/null'; then
+			echo 'Creating x2gouser group.' >&2
+			addgroup --system 'x2gouser'
 		else
-			echo "Group x2gouser already exists." >&2
+			echo 'Group x2gouser already exists.' >&2
 		fi
-		if ! getent passwd x2gouser >/dev/null; then
-			echo "Creating x2gouser user." >&2
+
+		if ! getent 'passwd' 'x2gouser' >'/dev/null'; then
+			echo 'Creating x2gouser user.' >&2
 			adduser --system --no-create-home \
 			        --disabled-password --disabled-login \
-			        --shell /bin/false --group --home /var/lib/x2go x2gouser
-
-			# make sure the home directory belongs to x2gouser:x2gouser
-			chown x2gouser:x2gouser /var/lib/x2go -Rf
+			        --shell '/bin/false' --group --home '/var/lib/x2go' 'x2gouser'
 		else
-			echo "User x2gouser already exists." >&2
+			echo 'User x2gouser already exists.' >&2
 			# make sure all settings are appropriate
-			if [ "`id -gn x2gouser`" != "x2gouser" ]; then
-				usermod --gid x2gouser x2gouser
-				test -d /var/lib/x2go && \
-					usermod --home /var/lib/x2go x2gouser || \
-					usermod --move-home --home /var/lib/x2go x2gouser
+			if [ "$(id -gn 'x2gouser')" != 'x2gouser' ]; then
+				usermod --gid 'x2gouser' 'x2gouser'
 			fi
-			if [ "`ls -1d ~x2gouser`" != "/var/lib/x2go" ]; then
-				usermod --move-home --home /var/lib/x2go x2gouser
+
+			if [ "$(getent 'passwd' 'x2gouser' | cut -d ':' -f '7')" != '/var/lib/x2go' ]; then
+				if [ -d '/var/lib/x2go' ]; then
+					usermod --home '/var/lib/x2go' 'x2gouser'
+				else
+					usermod --move-home --home '/var/lib/x2go' 'x2gouser'
+				fi
 			fi
+
 			# we leave user shell alone. we have never set this wrongly
 			# and we need to respect the administrator's choices
-
-			# make sure the home directory belongs to x2gouser:x2gouser
-			chown x2gouser:x2gouser /var/lib/x2go -Rf
 		fi
-		;;
 
-	abort-upgrade|abort-remove|abort-deconfigure)
+		# make sure the home directory belongs to x2gouser:x2gouser
+		chown -Rf 'x2gouser:x2gouser' '/var/lib/x2go'
 		;;
-
+	'abort-upgrade'|'abort-remove'|'abort-deconfigure')
+		;;
 	*)
-		echo "postinst called with unknown argument \`$1'" >&2
-		exit 1
+		echo "postinst called with unknown argument \`${1}'" >&2
+		exit '1'
 		;;
 esac
 
@@ -73,6 +71,4 @@ esac
 
 #DEBHELPER#
 
-exit 0
-
-
+exit '0'
diff --git a/debian/x2goserver-common.postrm b/debian/x2goserver-common.postrm
--- a/debian/x2goserver-common.postrm
+++ b/debian/x2goserver-common.postrm
@@ -15,20 +15,19 @@
 
 set -e
 
-case "$1" in
-	purge)
-		getent passwd x2gouser >/dev/null && deluser x2gouser
-		getent group x2gouser >/dev/null && delgroup x2gouser
-		getent group x2gousers >/dev/null && delgroup x2gousers
+case "${1}" in
+	'purge')
+		getent 'passwd' 'x2gouser' >'/dev/null' && deluser 'x2gouser'
+		getent 'group' 'x2gouser' >'/dev/null' && delgroup 'x2gouser'
+		getent 'group' 'x2gousers' >'/dev/null' && delgroup 'x2gousers'
 
-		rmdir --ignore-fail-on-non-empty /etc/x2go
-
+		rmdir --ignore-fail-on-non-empty '/etc/x2go'
 		;;
-	remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
+	'remove'|'upgrade'|'failed-upgrade'|'abort-install'|'abort-upgrade'|'disappear')
 		;;
 	*)
-		echo "postrm called with unknown argument \`$1'" >&2
-		exit 0
+		echo "postrm called with unknown argument \`${1}'" >&2
+		exit '0'
 		;;
 esac
 
@@ -37,4 +36,4 @@ esac
 
 #DEBHELPER#
 
-exit 0
+exit '0'
diff --git a/debian/x2goserver-fmbindings.postinst b/debian/x2goserver-fmbindings.postinst
--- a/debian/x2goserver-fmbindings.postinst
+++ b/debian/x2goserver-fmbindings.postinst
@@ -17,19 +17,16 @@ set -e
 # for details, see http://www.debian.org/doc/debian-policy/ or
 # the debian-policy package
 
-
-case "$1" in
-	configure)
+case "${1}" in
+	'configure')
 		update-desktop-database
-		update-mime-database /usr/share/mime
+		update-mime-database '/usr/share/mime'
 	;;
-
-	abort-upgrade|abort-remove|abort-deconfigure)
+	'abort-upgrade'|'abort-remove'|'abort-deconfigure')
 	;;
-
 	*)
-		echo "postinst called with unknown argument \`$1'" >&2
-		exit 1
+		echo "postinst called with unknown argument \`${1}'" >&2
+		exit '1'
 	;;
 esac
 
@@ -38,4 +35,4 @@ esac
 
 #DEBHELPER#
 
-exit 0
+exit '0'
diff --git a/debian/x2goserver-fmbindings.postrm b/debian/x2goserver-fmbindings.postrm
--- a/debian/x2goserver-fmbindings.postrm
+++ b/debian/x2goserver-fmbindings.postrm
@@ -18,16 +18,14 @@ set -e
 # for details, see http://www.debian.org/doc/debian-policy/ or
 # the debian-policy package
 
-
-case "$1" in
-	purge|remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
+case "${1}" in
+	'purge'|'remove'|'upgrade'|'failed-upgrade'|'abort-install'|'abort-upgrade'|'disappear')
 		update-desktop-database
-		update-mime-database /usr/share/mime
+		update-mime-database '/usr/share/mime'
 	;;
-
 	*)
-		echo "postrm called with unknown argument \`$1'" >&2
-		exit 1
+		echo "postrm called with unknown argument \`${1}'" >&2
+		exit '1'
 	;;
 esac
 
@@ -36,4 +34,4 @@ esac
 
 #DEBHELPER#
 
-exit 0
+exit '0'
diff --git a/debian/x2goserver-printing.postinst b/debian/x2goserver-printing.postinst
--- a/debian/x2goserver-printing.postinst
+++ b/debian/x2goserver-printing.postinst
@@ -17,69 +17,69 @@ set -e
 # for details, see http://www.debian.org/doc/debian-policy/ or
 # the debian-policy package
 
-
-case "$1" in
-	configure)
+case "${1}" in
+	'configure')
 		###
 		### X2Go printing
 		###
 
 		# setup x2goprint user and x2goprint group
-		if ! getent group x2goprint >/dev/null; then
-			echo "Creating x2goprint group." >&2
-			addgroup --system x2goprint
+		if ! getent 'group' 'x2goprint' >'/dev/null'; then
+			echo 'Creating x2goprint group.' >&2
+			addgroup --system 'x2goprint'
 		else
-			echo "Group x2goprint already exists." >&2
+			echo 'Group x2goprint already exists.' >&2
 		fi
-		if ! getent passwd x2goprint >/dev/null; then
-			echo "Creating x2goprint user." >&2
+
+		if ! getent 'passwd' 'x2goprint' >'/dev/null'; then
+			echo 'Creating x2goprint user.' >&2
 			adduser --system \
 			        --disabled-password --disabled-login \
-			        --shell /bin/sh --group --home /var/spool/x2goprint x2goprint
+			        --shell '/bin/sh' --group --home '/var/spool/x2goprint' 'x2goprint'
 		else
 			# make sure the home dir exists...
-			mkdir -p /var/spool/x2goprint/
+			mkdir -p '/var/spool/x2goprint/'
 
-			echo "User x2goprint already exists." >&2
+			echo 'User x2goprint already exists.' >&2
 			# make sure all settings are appropriate
-			if [ "`id -gn x2goprint`" != "x2goprint" ]; then
-				usermod --gid x2goprint x2goprint
+			if [ "$(id -gn 'x2goprint')" != 'x2goprint' ]; then
+				usermod --gid 'x2goprint' 'x2goprint'
 			fi
-			if getent passwd x2goprint | egrep -v ".*:x:.*:.*:.*:.*:/bin/sh" 1>/dev/null 2>/dev/null; then
-				usermod --shell /bin/sh x2goprint
+
+			if [ "$(getent 'passwd' 'x2goprint' | cut -d ':' -f '7')" != '/bin/sh' ]; then
+				usermod --shell '/bin/sh' 'x2goprint'
 			fi
-			if [ "`ls -1d ~x2goprint`" != "/var/spool/x2goprint" ]; then
-				if [ -d "/var/spool/x2goprint" ]; then
-					usermod --home /var/spool/x2goprint x2goprint
+
+			if [ "$(getent 'passwd' 'x2goprint' | cut -d ':' -f '6')" != '/var/spool/x2goprint' ]; then
+				if [ -d '/var/spool/x2goprint' ]; then
+					usermod --home '/var/spool/x2goprint' 'x2goprint'
 				else
-					usermod --move-home --home /var/spool/x2goprint x2goprint
+					usermod --move-home --home '/var/spool/x2goprint' 'x2goprint'
 				fi
 			fi
-			# we leave user shell alone. we have never set this wrongly
-			# and we need to respect the administrator's choices
-
 		fi
 
 		# make sure x2goprint spool dir permissions are set correctly
-		chown -R x2goprint:x2goprint /var/spool/x2goprint
+		chown -R 'x2goprint:x2goprint' '/var/spool/x2goprint'
+
 		# egid x2goprint needs write access to the spool dir
-		chmod 0700 /var/spool/x2goprint
+		chmod '0700' '/var/spool/x2goprint'
 
 		# we may be upgrading versions of x2goserver that had
 		# /usr/bin/x2goprint set to setuid x2goprint.
-		if dpkg-statoverride --list /usr/bin/x2goprint >/dev/null; then
-			dpkg-statoverride --remove /usr/bin/x2goprint
-			chown root:root /usr/bin/x2goprint
-			chmod 0755 /usr/bin/x2goprint
+		if dpkg-statoverride --list '/usr/bin/x2goprint' >'/dev/null'; then
+			dpkg-statoverride --remove '/usr/bin/x2goprint'
+			chown 'root:root' '/usr/bin/x2goprint'
+			chmod '0755' '/usr/bin/x2goprint'
 		fi
 		;;
 
-	abort-upgrade|abort-remove|abort-deconfigure)
+	'abort-upgrade'|'abort-remove'|'abort-deconfigure')
 		;;
 
 	*)
-		echo "postinst called with unknown argument \`$1'" >&2
-		exit 1
+		echo "postinst called with unknown argument \`${1}'" >&2
+		exit '1'
 		;;
 esac
 
@@ -88,6 +88,4 @@ esac
 
 #DEBHELPER#
 
-exit 0
-
-
+exit '0'
diff --git a/debian/x2goserver-printing.postrm b/debian/x2goserver-printing.postrm
--- a/debian/x2goserver-printing.postrm
+++ b/debian/x2goserver-printing.postrm
@@ -1,6 +1,8 @@
 #! /bin/sh
 # postrm script for x2goserver-printing
-#
+
+set -e
+
 # see: dh_installdeb(1)
 # summary of how this script can be called:
 #        * <postrm> `remove'
@@ -10,22 +12,20 @@
 #        * <new-postrm> `abort-install'
 #        * <new-postrm> `abort-install' <old-version>
 #        * <new-postrm> `abort-upgrade' <old-version>
-#        * <disappearer's-postrm> `disappear' <r>overwrit>r> <new-version>
+#        * <disappearer's-postrm> `disappear' <overwriter>
+#          <overwriter-version>
 # for details, see /usr/share/doc/packaging-manual/
 
-set -e
-
-
-case "$1" in
-	purge)
-		getent passwd x2goprint >/dev/null && deluser x2goprint
-		getent group x2goprint >/dev/null && delgroup x2goprint
+case "${1}" in
+	'purge')
+		getent 'passwd' 'x2goprint' >'/dev/null' && deluser 'x2goprint'
+		getent 'group' 'x2goprint' >'/dev/null' && delgroup 'x2goprint'
 		;;
-	remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
+	'remove'|'upgrade'|'failed-upgrade'|'abort-install'|'abort-upgrade'|'disappear')
 		;;
 	*)
-		echo "postrm called with unknown argument \`$1'" >&2
-		exit 0
+		echo "postrm called with unknown argument \`${1}'" >&2
+		exit '0'
 		;;
 esac
 
@@ -34,4 +34,4 @@ esac
 
 #DEBHELPER#
 
-exit 0
+exit '0'
diff --git a/debian/x2goserver.postinst b/debian/x2goserver.postinst
--- a/debian/x2goserver.postinst
+++ b/debian/x2goserver.postinst
@@ -6,7 +6,7 @@
 set -e
 
 # Source debconf library.
-. /usr/share/debconf/confmodule
+. '/usr/share/debconf/confmodule'
 
 # summary of how this script can be called:
 #        * <postinst> `configure' <most-recently-configured-version>
@@ -20,41 +20,39 @@ set -e
 # for details, see http://www.debian.org/doc/debian-policy/ or
 # the debian-policy package
 
-
-case "$1" in
-	configure)
-
-		### cleaning ab setgid stuff of older versions of package x2goserver
+case "${1}" in
+	'configure')
+		### cleaning up setgid stuff of older versions of package x2goserver
 
 		# we may be upgrading from versions of x2goserver that had
 		# /usr/lib/x2go/x2gosqlitewrapper.pl set to setuid x2gouser. This script is
 		# not at that location anymore, we clear the dpkg-statoverride entry.
-		if dpkg-statoverride --list /usr/lib/x2go/x2gosqlitewrapper.pl >/dev/null; then
-			dpkg-statoverride --remove /usr/lib/x2go/x2gosqlitewrapper.pl
+		if dpkg-statoverride --list '/usr/lib/x2go/x2gosqlitewrapper.pl' >'/dev/null'; then
+			dpkg-statoverride --remove '/usr/lib/x2go/x2gosqlitewrapper.pl'
 		fi
 
 		# we may be upgrading from versions of x2goserver that had
 		# /usr/bin/x2gosqlitewrapper set to setuid or setgid x2gouser, the script itself is not
 		# at this location anymore, we just clear the dpkg-statoverride config entry.
-		if dpkg-statoverride --list /usr/bin/x2gosqlitewrapper >/dev/null; then
-			dpkg-statoverride --remove /usr/bin/x2gosqlitewrapper
+		if dpkg-statoverride --list '/usr/bin/x2gosqlitewrapper' >'/dev/null'; then
+			dpkg-statoverride --remove '/usr/bin/x2gosqlitewrapper'
 		fi
 
 		# we may be upgrading from versions of x2goserver that had
 		# /usr/lib/x2go/x2gosqlitewrapper set to setgid x2gouser, the script itself is not
 		# at this location anymore, we just clear the dpkg-statoverride config entry.
-		if dpkg-statoverride --list /usr/lib/x2go/x2gosqlitewrapper >/dev/null; then
-		    dpkg-statoverride --remove /usr/lib/x2go/x2gosqlitewrapper
+		if dpkg-statoverride --list '/usr/lib/x2go/x2gosqlitewrapper' >'/dev/null'; then
+		    dpkg-statoverride --remove '/usr/lib/x2go/x2gosqlitewrapper'
 		fi
 
 		# sudoers.d files have to be installed 0440:root:root
-		if ! dpkg-statoverride --list /etc/sudoers.d/x2goserver >/dev/null; then
-		    dpkg-statoverride --add --update root root 0440 /etc/sudoers.d/x2goserver
+		if ! dpkg-statoverride --list '/etc/sudoers.d/x2goserver' >'/dev/null'; then
+		    dpkg-statoverride --add --update 'root' 'root' '0440' '/etc/sudoers.d/x2goserver'
 		fi
 
 		# create /etc/x2go/applications symlink if not already there (as link or as dir)
-		if ! test -e /etc/x2go/applications; then
-			ln -s /usr/share/applications /etc/x2go/applications
+		if ! test -e '/etc/x2go/applications'; then
+			ln -s '/usr/share/applications' '/etc/x2go/applications'
 		fi
 
 		# Setup up SQLite3 database, do nothing if PostgeSQL is already configured
@@ -63,29 +61,26 @@ case "$1" in
 		# It will only succeed if both packages are installed. As we cannot influence the
 		# installation order, we handle the session DB creation in both packages. One of
 		# then should succeed.
-		if [ -f /etc/x2go/x2gosql/sql ] && egrep "^backend=sqlite.*" /etc/x2go/x2gosql/sql >/dev/null; then
-			if [ ! -f /var/lib/x2go/x2go_sessions ]; then
+		if [ -f '/etc/x2go/x2gosql/sql' ] && grep -Eq '^backend=sqlite.*' '/etc/x2go/x2gosql/sql' >'/dev/null'; then
+			if [ ! -f '/var/lib/x2go/x2go_sessions' ]; then
 				x2godbadmin --createdb
 			else
 				# make sure db permissions are set correctly
-				chown -R root:x2gouser /var/lib/x2go
+				chown -R 'root:x2gouser' '/var/lib/x2go'
 				# egid x2gouser needs write access to the db dir (for temporary db journal file)
-				chmod 0770 /var/lib/x2go
+				chmod '0770' '/var/lib/x2go'
 				# ... and to the db file itself, of course
-				chmod 0660 /var/lib/x2go/x2go_sessions
+				chmod '0660' '/var/lib/x2go/x2go_sessions'
 			fi
 		else
 			echo "X2Go is configured to use a non-SQLite DB backend, leaving the database alone."
 		fi
-
 		;;
-
-	abort-upgrade|abort-remove|abort-deconfigure)
+	'abort-upgrade'|'abort-remove'|'abort-deconfigure')
 		;;
-
 	*)
-		echo "postinst called with unknown argument \`$1'" >&2
-		exit 1
+		echo "postinst called with unknown argument \`${1}'" >&2
+		exit '1'
 		;;
 esac
 
@@ -94,4 +89,4 @@ esac
 
 #DEBHELPER#
 
-exit 0
+exit '0'
diff --git a/debian/x2goserver.postrm b/debian/x2goserver.postrm
--- a/debian/x2goserver.postrm
+++ b/debian/x2goserver.postrm
@@ -1,6 +1,8 @@
 #! /bin/sh
 # postrm script for x2goserver
-#
+
+set -e
+
 # see: dh_installdeb(1)
 # summary of how this script can be called:
 #        * <postrm> `remove'
@@ -10,27 +12,25 @@
 #        * <new-postrm> `abort-install'
 #        * <new-postrm> `abort-install' <old-version>
 #        * <new-postrm> `abort-upgrade' <old-version>
-#        * <disappearer's-postrm> `disappear' <r>overwrit>r> <new-version>
+#        * <disappearer's-postrm> `disappear' <overwriter>i
+#          <overwriter-version>
 # for details, see /usr/share/doc/packaging-manual/
 
-set -e
-
-
-case "$1" in
-	purge)
-		if dpkg-statoverride --list /etc/sudoers.d/x2goserver >/dev/null; then
-			dpkg-statoverride --remove /etc/sudoers.d/x2goserver
+case "${1}" in
+	'purge')
+		if dpkg-statoverride --list '/etc/sudoers.d/x2goserver' >'/dev/null'; then
+			dpkg-statoverride --remove '/etc/sudoers.d/x2goserver'
 		fi
 
-		rm -Rf /etc/x2go/applications
-		rm -Rf /etc/x2go/x2go_logout.d
-		rmdir --ignore-fail-on-non-empty /etc/x2go
+		rm -Rf '/etc/x2go/applications'
+		rm -Rf '/etc/x2go/x2go_logout.d'
+		rmdir --ignore-fail-on-non-empty '/etc/x2go'
 		;;
-	remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
+	'remove'|'upgrade'|'failed-upgrade'|'abort-install'|'abort-upgrade'|'disappear')
 		;;
 	*)
-		echo "postrm called with unknown argument \`$1'" >&2
-		exit 0
+		echo "postrm called with unknown argument \`${1}'" >&2
+		exit '0'
 		;;
 esac
 
@@ -39,4 +39,4 @@ esac
 
 #DEBHELPER#
 
-exit 0
+exit '0'
