x2goserver/bin/x2go{resume-session,startagent}: revert error catching while inserting values into database.
The current code structure relies on ignoring failures and retrying
until an operation succeeded, which may eventually happen or just as
well may never happen.

We need something smarter here.

Cherry-picked from release/4.0.1.x branch.

diff --git a/x2goserver/bin/x2goresume-session b/x2goserver/bin/x2goresume-session
--- a/x2goserver/bin/x2goresume-session
+++ b/x2goserver/bin/x2goresume-session
@@ -236,14 +236,16 @@ while [ "$GR_PORT" == "" ] || [ "$SOUND_PORT" == "" ] || [ "$FS_PORT" == "" ] ||
 		if [ "$SERV" == "" ]; then
 			OUTPUT="$("${X2GO_LIB_PATH}/x2goinsertport" "${current_host_name}" "$SESSION_NAME" "$SSH_PORT")"
 
-			if [[ "${?}" -ne "0" ]]; then
-				typeset msg="Unable to insert new port into database; parameters: hostname (${current_host_name}), session name (${SESSION_NAME}) and port (${SSH_PORT})."
-				"${X2GO_LIB_PATH}/x2gosyslog" "${0}" "err" "${msg}"
-
-				# Make x2goclient fail.
-				echo "${msg}" >&2
-				exit 1
-			fi
+			# Catching errors here would be nice, but the current layout doesn't allow this.
+			# Keep this in mind as a FIXME.
+			#if [[ "${?}" -ne "0" ]]; then
+			#	typeset msg="Unable to insert new port into database; parameters: hostname (${current_host_name}), session name (${SESSION_NAME}) and port (${SSH_PORT})."
+			#	"${X2GO_LIB_PATH}/x2gosyslog" "${0}" "err" "${msg}"
+			#
+			#	# Make x2goclient fail.
+			#	echo "${msg}" >&2
+			#	exit 1
+			#fi
 		fi
 	done
 	if [ "$GR_PORT" == "" ]; then
