x2gostartagent, x2golistsession, x2gosuspend-session and x2goresume-session getting agent state from ~/.x2go/C-$SID/state. This should help to avoid session damage. Remove nxcleanup.

diff --git a/x2goserver/bin/x2gosuspend-session b/x2goserver/bin/x2gosuspend-session
--- a/x2goserver/bin/x2gosuspend-session
+++ b/x2goserver/bin/x2gosuspend-session
@@ -45,26 +45,30 @@ x2gofeature X2GO_RUN_EXTENSIONS &>/dev/null && x2goserver-run-extensions "$SESSI
 export HOSTNAME
 x2goumount-session "$SESSION_NAME"
 
-if kill -HUP $X2GO_AGENT_PID &>/dev/null; then
-	$X2GO_LIB_PATH/x2gosyslog "$0" "notice" "session with ID $SESSION_NAME has been suspended successfully"
+STATE=`$X2GO_LIB_PATH/x2gogetagentstate "$SESSION_NAME"`
 
-	# run x2goserver-extensions for post-suspend
-	x2gofeature X2GO_RUN_EXTENSIONS &>/dev/null && x2goserver-run-extensions "$SESSION_NAME" post-suspend || true
+if [ "$STATE" == "RESUMING" ] || [ "$STATE" == "STARTING" ] || [ "$STATE" == "RUNNING" ]
+then
+	if kill -HUP $X2GO_AGENT_PID &>/dev/null; then
+		$X2GO_LIB_PATH/x2gosyslog "$0" "notice" "session with ID $SESSION_NAME has been suspended successfully"
 
-	$X2GO_LIB_PATH/x2gochangestatus 'S' "$SESSION_NAME"  > /dev/null
+		# run x2goserver-extensions for post-suspend
+		x2gofeature X2GO_RUN_EXTENSIONS &>/dev/null && x2goserver-run-extensions "$SESSION_NAME" post-suspend || true
 
-	# this makes sure that the socket on localhost blocked by NX agent gets released immediately
-	$X2GO_LIB_PATH/x2gonxcleanup
+		$X2GO_LIB_PATH/x2gochangestatus 'S' "$SESSION_NAME"  > /dev/null
+
+	else
+		err_msg="ERROR: failed to suspend session with ID $SESSION_NAME"
+		echo "$err_msg" 1>&2
+		$X2GO_LIB_PATH/x2gosyslog "$0" "err" "$err_msg"
+
+		# run x2goserver-extensions for fail-suspend
+		x2gofeature X2GO_RUN_EXTENSIONS &>/dev/null && x2goserver-run-extensions "$SESSION_NAME" fail-suspend || true
+
+		# If we reach here it means that the x2goagent process of the session has vanisshed
+		# If this happens then we mark the session as finished...
+		$X2GO_LIB_PATH/x2gochangestatus 'F' "$SESSION_NAME"  > /dev/null
+	fi
 else
-	err_msg="ERROR: failed to suspend session with ID $SESSION_NAME"
-	echo "$err_msg" 1>&2
-	$X2GO_LIB_PATH/x2gosyslog "$0" "err" "$err_msg"
-
-	# run x2goserver-extensions for fail-suspend
-	x2gofeature X2GO_RUN_EXTENSIONS &>/dev/null && x2goserver-run-extensions "$SESSION_NAME" fail-suspend || true
-
-	# If we reach here it means that the x2goagent process of the session has vanisshed
-	# If this happens then we mark the session as finished...
-	$X2GO_LIB_PATH/x2gochangestatus 'F' "$SESSION_NAME"  > /dev/null
+	$X2GO_LIB_PATH/x2gosyslog "$0" "notice" "session with ID $SESSION_NAME is not in running state"
 fi
-
