x2goserver/bin/x2goresume-session: catch errors while inserting values into database more gracefully. Fixes: #1230.
Cherry-picked from release/4.0.1.x branch.

diff --git a/x2goserver/bin/x2gostartagent b/x2goserver/bin/x2gostartagent
--- a/x2goserver/bin/x2gostartagent
+++ b/x2goserver/bin/x2gostartagent
@@ -341,11 +341,29 @@ while [ "$OUTPUT"  != "inserted" ]; do
 		if [ -n "$SHADREQ_USER" ]; then
 			$X2GO_LIB_PATH/x2gosyslog "$0" "debug" "initializing new shadow session with ID $SESSION_NAME"
 			OUTPUT=`$X2GO_LIB_PATH/x2goinsertshadowsession "$X2GO_PORT" "${current_host_name}" "$SESSION_NAME" "$SHADREQ_USER"`
+
+			if [[ "${?}" -ne "0" ]]; then
+				typeset msg="Unable to insert new session into database; parameters: port (${X2GO_PORT}), hostname (${current_host_name}), session name (${SESSION_NAME}) and user requesting desktop sharing permissions (${SHADREQ_USER})."
+				"${X2GO_LIB_PATH}/x2gosyslog" "${0}" "err" "${msg}"
+
+				# Make x2goclient fail.
+				echo "${msg}" >&2
+				exit 1
+			fi
 		else
 			$X2GO_LIB_PATH/x2gosyslog "$0" "debug" "initializing new session with ID $SESSION_NAME"
 			OUTPUT=`$X2GO_LIB_PATH/x2goinsertsession "$X2GO_PORT" "${current_host_name}" "$SESSION_NAME"`
+
+			if [[ "${?}" -ne "0" ]]; then
+				typeset msg="Unable to insert new session into database; parameters: port (${X2GO_PORT}), hostname (${current_host_name}) and session name (${SESSION_NAME})."
+				"${X2GO_LIB_PATH}/x2gosyslog" "${0}" "err" "${msg}"
+
+				# Make x2goclient fail.
+				echo "${msg}" >&2
+				exit 1
+			fi
 		fi
-	fi 
+	fi
 done
 
 if [ "x$X2GO_TELEKINESIS_ENABLED" == "x0" ] || [ "x$X2GO_STYPE" = "xS" ] || ! type -p telekinesis-server 1>/dev/null; then
@@ -373,6 +391,15 @@ while [ "$GR_PORT" == "" ] || [ "$SOUND_PORT" == "" ] || [ "$FS_PORT" == "" ] ||
 		SERV=`grep $SSH_PORT /etc/services`
 		if [ "$SERV" == "" ]; then
 			OUTPUT=`$X2GO_LIB_PATH/x2goinsertport "${current_host_name}" "$SESSION_NAME" "$SSH_PORT"`
+
+			if [[ "${?}" -ne "0" ]]; then
+				typeset msg="Unable to insert new port into database; parameters: hostname (${current_host_name}), session name (${SESSION_NAME}) and port (${SSH_PORT})."
+				"${X2GO_LIB_PATH}/x2gosyslog" "${0}" "err" "${msg}"
+
+				# Make x2goclient fail.
+				echo "${msg}" >&2
+				exit 1
+			fi
 		fi
 	done
 
